openapi: 3.0.0
info:
  title: Exchange API
  description: >
    API for activating two-factor authentication (2FA).  
    **Note:** To make API calls using Node.js, you must install the **alphapoint-apex-api** library:

    ```
    npm install alphapoint-apex-api
    ```
  version: 1.0.0

servers:
  - url: https://api.exchange.com

paths:
  /activate2fa:
    post:
      summary: Activate 2FA
      description: Completes two-factor authentication (2FA) activation by sending the verification code.
      operationId: activate2fa
      tags:
        - Activation
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Code:
                  type: string
                  description: The alphanumeric authentication code received.
              required:
                - Code
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Activated:
                    type: boolean
                    description: true if the activation code is accepted, false otherwise.
                  Error:
                    type: string
                    description: Error message in case of failure.
        "400":
          description: Bad request
        "401":
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: APIKey

x-examples:
  curl: |
    curl -X POST https://api.exchange.com/activate2fa \
      -H "Content-Type: application/json" \
      -H "APIKey: your_api_key" \
      -H "Signature: your_signature" \
      -H "UserId: your_user_id" \
      -H "Nonce: your_nonce" \
      -d '{
        "Code": "YourCode"
      }'

  javascript: |
    fetch("https://api.exchange.com/activate2fa", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "APIKey": getEnvVar("APIKey"),
        "Signature": getEnvVar("Signature"),
        "UserId": getEnvVar("UserId"),
        "Nonce": getEnvVar("Nonce"),
      },
      body: JSON.stringify({ Code: "YourCode" }),
    })
    .then(response => response.json())
    .then(data => console.log(data))
    .catch(error => console.error("Error:", error));

  typescript: |
    import fetch from "node-fetch";

    interface Activate2FAResponse {
      Activated: boolean;
      Error?: string;
    }

    async function activate2FA(code: string): Promise<void> {
      const response = await fetch("wss://api.kiire.apstage.net/WSGateway/Activate2FA", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "APIKey": process.env.APIKey!,
          "Signature": process.env.Signature!,
          "UserId": process.env.UserId!,
          "Nonce": process.env.Nonce!,
        },
        body: JSON.stringify({ Code: code }),
      });

      const data: Activate2FAResponse = await response.json();
      console.log(data);
    }

    activate2FA("YourCode");
