openapi: 3.0.0
info:
  title: KIIEX API
  description: >
    API for completing two-factor authentication (2FA).  
    **Note:** To make API calls using Node.js, you must install the **alphapoint-apex-api** library:
    
    ```
    npm install alphapoint-apex-api
    ```
  version: 1.0.0

servers:
  - url: https://api.kiiex.com

paths:
  /authenticate2fa:
    post:
      summary: Authenticate 2FA
      description: >
        Completes the second part of two-factor authentication (2FA) by sending the authentication token 
        from a third-party authentication system to the Order Management System (OMS).  
        **Process:**  
        1. Call `webauthenticateuser` to obtain `TwoFAType` and `TwoFAToken`.  
        2. Use `TwoFAToken` in your authentication app (e.g., Google Authenticator).  
        3. The authentication app returns a new token.  
        4. Call `authenticate2FA` with the new token.  
      operationId: authenticate2FA
      tags:
        - Authentication
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Code:
                  type: string
                  description: Token obtained from the third-party authentication source.
              required:
                - Code
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  Authenticated:
                    type: boolean
                    description: true if authentication is successful, false otherwise.
                  SessionToken:
                    type: string
                    description: >
                      The session token is valid for the current session from the same IP address. 
                      It lasts for **one hour** after the last activity or until logout.  
                      Use this token to reconnect without repeating the full 2FA process.
        "400":
          description: Bad request
        "401":
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: APIKey

x-examples:
  curl: |
    curl -X POST wss://api.kiire.apstage.net/WSGateway/authenticate2fa \
      -H "Content-Type: application/json" \
      -H "APIKey: your_api_key" \
      -H "Signature: your_signature" \
      -H "UserId: your_user_id" \
      -H "Nonce: your_nonce" \
      -d '{
        "Code": "YourCode"
      }'

  javascript: |
    fetch("wss://api.kiire.apstage.net/WSGateway/authenticate2fa", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "APIKey": getEnvVar("APIKey"),
        "Signature": getEnvVar("Signature"),
        "UserId": getEnvVar("UserId"),
        "Nonce": getEnvVar("Nonce"),
      },
      body: JSON.stringify({
        Code: "YourCode",
      }),
    })
    .then(response => response.json())
    .then(data => console.log(data))
    .catch(error => console.error("Error:", error));
