openapi: 3.0.0
info:
  title: Cancel All Orders
  description: Cancels all open matching orders for an account.
  version: 1.0.0
paths:
  CancelAllOrders:
    post: # Use POST for actions that modify data
      summary: Cancel All Orders
      tags:
        - User
      requestBody: # Define the request body
        content:
          application/json:
            schema:
              type: object
              properties:
                AccountId:
                  type: integer
                  description: The account ID.
                OMSId:
                  type: integer
                  description: The Order Management System ID.
                  required: true # OMSId is required
              example:
                AccountId: 0
                OMSId: 0
      responses:
        "200":
          description: Successful cancellation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: True if successful, false otherwise.
                  errormsg:
                    type: string
                    description: Error message (empty string if successful).
                  errorcode:
                    type: integer
                    description: Error code (0 if successful).
                  detail:
                    type: string
                    description: Additional details.
                example:
                  result: true
                  errormsg: ""
                  errorcode: 0
                  detail: ""
