openapi: 3.0.0
info:
  title: Cancel User Report API
  description: API endpoint to cancel a scheduled user report using its report ID (GUID).
  version: 1.0.0
paths:
  /cancelUserReport:
    post:
      summary: Cancels a scheduled user report by its report ID
      description: |
        You can cancel a scheduled user report by providing its unique GUID. 
        The response confirms the receipt of the cancellation request but does not guarantee the cancellation's success. 
        To verify, use `GetUserReportTickets` or `GetUserReportWriterResultRecords`.
      tags:
        - Users
      operationId: cancelUserReport
      requestBody:
        description: The GUID of the user report to be canceled.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                UserReportId:
                  type: string
                  description: A globally unique ID string identifying the user report to cancel.
              required:
                - UserReportId
      responses:
        '200':
          description: Cancellation request successfully received
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    description: |
                      true if the cancellation request was received successfully, 
                      false otherwise.
                  errormsg:
                    type: string
                    description: |
                      Error message if the cancellation was unsuccessful. 
                      Possible values include:
                        - Not Authorized (errorcode 20)
                        - Invalid Request (errorcode 100)
                        - Operation Failed (errorcode 101)
                        - Server Error (errorcode 102)
                        - Resource Not Found (errorcode 104)
                  errorcode:
                    type: integer
                    description: |
                      Error code corresponding to the `errormsg`.
                      `0` indicates successful receipt of the cancellation.
                  detail:
                    type: string
                    description: Additional information or null.
        '400':
          description: Invalid request due to missing or malformed data
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: false
                  errormsg:
                    type: string
                    example: Invalid Request
                  errorcode:
                    type: integer
                    example: 100
                  detail:
                    type: string
                    example: Missing required 
                    parameter: UserReportId
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: false
                  errormsg:
                    type: string
                    example: Not Authorized
                  errorcode:
                    type: integer
                    example: 20
