openapi: 3.0.0
info:
  title: Get All Unredacted User Configs For User
  description: Gets all the unredacted configs for a user.
  version: 1.0.0
paths:
  GetAllUnredactedUserConfigsForUser: # Or a more suitable path
    get:
      summary: Get All Unredacted User Configs
      tags:
        - System
      parameters:
        - in: query
          name: userId
          schema:
            type: integer
          description: The ID of the user.
          required: true
        - in: query
          name: userName
          schema:
            type: string
          description: The user name of the user.
          required: true
      responses:
        '200':
          description: Successful retrieval of unredacted user configurations.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Key:
                      type: string
                      description: The configuration key.
                    Value:
                      type: string
                      description: The configuration value.
              example:
                - Key: "Config1"
                  Value: "Config1Val"
                - Key: "Setting2"
                  Value: "Value2"
                - Key: "API_KEY"
                  Value: "Actual_API_KEY" # Example of an *unredacted* value