openapi: 3.0.0
info:
  title: Get Account Withdraw Transactions
  description: Obtains a list of withdrawals for an account.
  version: 1.0.0
paths:
  GetAccountWithdrawTransactions:
    get:
      summary: Get Account Withdraw Transactions
      tags:
        - User
      parameters:
        - in: query
          name: OMSId
          schema:
            type: integer
          description: The ID of the Order Management System.
          required: true
        - in: query
          name: AccountId
          schema:
            type: integer
          description: The account ID.
          required: true
        - in: query
          name: Depth
          schema:
            type: integer
          description: The count of withdrawal transactions to return.
      responses:
        "200":
          description: Successful retrieval of withdrawal transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: integer
                      description: The ID of the transaction.
                    omsId:
                      type: integer
                      description: The ID of the Order Management System.
                    accountId:
                      type: integer
                      description: The account ID.
                    cr:
                      type: number
                      format: float
                      description: Credit entry.
                    dr:
                      type: number
                      format: float
                      description: Debit entry.
                    counterparty:
                      type: integer
                      description: The counterparty.
                    transactionType:
                      type: integer
                      enum:
                        - 1 # Fee
                        - 2 # Trade
                        - 3 # Other
                        - 4 # Reverse
                        - 5 # Hold
                        - 6 # Rebate
                        - 7 # MarginAcquisition
                        - 8 # MarginRelinquish
                      description: The transaction type.
                    referenceId:
                      type: integer
                      description: The ID of the triggering action.
                    referenceType:
                      type: integer
                      enum:
                        - 1 # Trade
                        - 2 # Deposit
                        - 3 # Withdraw
                        - 4 # Transfer
                        - 5 # OrderHold
                        - 6 # WithdrawHold
                        - 7 # DepositHold
                        - 8 # MarginHold
                        - 9 # ManualHold
                        - 10 # ManualEntry
                        - 11 # MarginAcquisition
                        - 12 # MarginRelinquish
                        - 13 # MarginQuoteHold
                      description: The type of triggering action.
                    productId:
                      type: integer
                      description: The product ID.
                    balance:
                      type: number
                      format: float
                      description: The account balance.
                    timeStamp:
                      type: integer
                      description: The timestamp (POSIX format).
                  required:
                    - transactionId
                    - omsId
                    - accountId
                    - cr
                    - dr
                    - counterparty
                    - transactionType
                    - referenceId
                    - referenceType
                    - productId
                    - balance
                    - timeStamp
                  example:
                    transactionId: 0
                    omsId: 0
                    accountId: 0
                    cr: 0.0
                    dr: 0.0
                    counterparty: 0
                    transactionType: 0
                    referenceId: 0
                    referenceType: 0
                    productId: 0
                    balance: 0.0
                    timeStamp: 0
