openapi: 3.0.0
info:
  title: Get Level 2 Snapshot API
  description: Provides a Level 2 snapshot of a specific instrument's order book with user-defined market depth.
  version: 1.0.0
paths:
  /getL2Snapshot:
    post:
      summary: Get Level 2 snapshot for a specific instrument
      description: |
        Provides a current Level 2 snapshot of a specific instrument trading on an Order Management System (OMS) to a user-specified market depth.
        The snapshot includes buyers and sellers at greater or lesser prices in the order book.
      tags:
        - Users
      operationId: getL2Snapshot
      requestBody:
        description: Input parameters to specify the OMS, instrument, and desired market depth.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OMSId:
                  type: integer
                  description: The ID of the Order Management System where the instrument is traded.
                  example: 1
                InstrumentId:
                  type: integer
                  description: The ID of the instrument for which the snapshot is requested.
                  example: 1
                Depth:
                  type: integer
                  description: |
                    Depth of the market — the number of buyers and sellers at greater or lesser prices in the order book. 
                    Defaults to 100 if not provided.
                  example: 100
              required:
                - OMSId
                - InstrumentId
      responses:
        '200':
          description: Successful Level 2 snapshot
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    type: number
                  description: |
                    Array containing Level 2 snapshot data. Each array element represents a market depth entry.
                    The elements correspond to:
                      - Account Id (integer)
                      - ActionDateTime (long integer)
                      - ActionType (integer: 0=New, 1=Update, 2=Delete)
                      - LastTradePrice (real)
                      - OrderId (integer)
                      - Price (real)
                      - ProductPairCode (integer)
                      - Quantity (real)
                      - Side (integer: 0=Buy, 1=Sell, 2=Short, 3=Unknown)
                example: 
                  [
                    [1, 123, 0, 0.0, 0, 0.0, 0, 0.0, 0]
                  ]
        '400':
          description: Invalid request due to missing or malformed parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing required 
                    parameter: OMSId
