openapi: 3.0.0
info:
  title: Get Level 1
  description: >
    Provides a current Level 1 snapshot (best bid, best offer) of a specific 
    instrument trading on an Order Management System. The Level 1 snapshot does 
    not allow the user to specify the level of market depth information on either 
    side of the bid and ask.
  version: 1.0.0
paths:
  /GetLevel1: # Define the path for the API endpoint
    get: # Specify the HTTP method (GET in this case)
      summary: Get Level 1 Data # Short summary of the operation
      tags: # Organize operations with tags
        - User
      parameters: # Define the request parameters (query parameters for GET)
        - in: query
          name: OMSId
          schema:
            type: integer
          description: The ID of the Order Management System.
          required: true
        - in: query
          name: InstrumentId
          schema:
            type: integer
          description: The ID of the instrument.
          required: true
      responses:
        "200": # Define the successful response code
          description: Successful Level 1 data retrieval
          content:
            application/json: # Specify the response content type
              schema:
                type: object
                properties:
                  exchangeId:
                    type: integer
                    description: The ID of the exchange.
                  productPairCode:
                    type: integer
                    description: The ID of the instrument.
                  bestBid:
                    type: number # Use 'number' for real/float values
                    format: float # Explicitly define the format
                    description: The current best bid.
                  bestOffer:
                    type: number
                    format: float
                    description: The current best offer.
                  volume:
                    type: number
                    format: float
                    description: The unit volume traded.
                  lastTradedPx:
                    type: number
                    format: float
                    description: The last-traded price.
                  lastTradedVolume:
                    type: number
                    format: float
                    description: The last quantity traded.
                  lastTradeTime:
                    type: integer # Time is usually an integer (Unix timestamp)
                    description: The last trade time.
                  timeStamp:
                    type: integer # Timestamp should also be an integer
                    description: The date and time of the snapshot.
                  bidQty:
                    type: number
                    format: float
                    description: The quantity currently being bid.
                  askQty:
                    type: number
                    format: float
                    description: The quantity currently being asked.
                  bidOrderCt:
                    type: integer
                    description: The count of bid orders.
                  askOrderCt:
                    type: integer
                    description: The count of ask orders.
                  sessionOpen:
                    type: number
                    format: float
                    description: Opening price.
                  sessionHigh:
                    type: number
                    format: float
                    description: Highest price.
                  sessionLow:
                    type: number
                    format: float
                    description: Lowest price.
                  sessionClose:
                    type: number
                    format: float
                    description: The closing price.
                  currentDayVolume:
                    type: number
                    format: float
                    description: The unit volume of the instrument.
                  currentDayNumTrades:
                    type: integer
                    description: The number of trades.
                  currentDayPxChange:
                    type: number
                    format: float
                    description: Change in price.
                  rolling24HrVolume:
                    type: number
                    format: float
                    description: Unit volume over the past 24 hours.
                  rolling24HrNumTrades:
                    type: number
                    format: float
                    description: Number of trades during the past 24 hours.
                  rolling24HrPxChange:
                    type: number
                    format: float
                    description: Price change during the past 24 hours.
                  rolling24HrPxChangePercent:
                    type: number
                    format: float
                    description: Percent change in price during the past 24 hours.
                example: # Example response
                  exchangeId: 0
                  productPairCode: 0
                  bestBid: 0.0
                  bestOffer: 0.0
                  volume: 0.0
                  lastTradedPx: 0.0
                  lastTradedVolume: 0.0
                  lastTradeTime: 0
                  timeStamp: 0
                  bidQty: 0.0
                  askQty: 0.0
                  bidOrderCt: 0
                  askOrderCt: 0
                  sessionOpen: 0.0
                  sessionHigh: 0.0
                  sessionLow: 0.0
                  sessionClose: 0.0
                  currentDayVolume: 0.0
                  currentDayNumTrades: 0
                  currentDayPxChange: 0.0
                  rolling24HrVolume: 0.0
                  rolling24HrNumTrades: 0.0
                  rolling24HrPxChange: 0.0
                  rolling24HrPxChangePercent: 0.0
