openapi: 3.0.0
info:
  title: Get OMS Withdraw Fees
  description: Returns fees assessed on a specific product.
  version: 1.0.0
paths:
  GetOMSWithdrawFees:
    get:
      summary: Get OMS Withdraw Fees
      tags:
        - User
      parameters:
        - in: query
          name: OMSId
          schema:
            type: integer
          description: The ID of the Order Management System.
          required: true
        - in: query
          name: ProductId
          schema:
            type: integer
          description: The product ID.
          required: true
      responses:
        "200":
          description: Successful retrieval of withdraw fees.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    OMSId:
                      type: integer
                      description: The Order Management System ID.
                    AccountId:
                      type: integer
                      description: The account ID.
                    FeeId:
                      type: integer
                      description: The fee ID.
                    FeeAmt:
                      type: number
                      format: float
                      description: The fee amount.
                    FeeCalcType:
                      type: string
                      enum:
                        - Percentage
                        - FlatRate
                      description: The fee calculation type.
                    IsActive:
                      type: boolean
                      description: Is the fee active?
                    ProductId:
                      type: integer
                      description: The product ID.
                  required:
                    - OMSId
                    - AccountId
                    - FeeId
                    - FeeAmt
                    - FeeCalcType
                    - IsActive
                    - ProductId
                  example:
                    OMSId: 1
                    AccountId: 0
                    FeeId: 47
                    FeeAmt: 1.0 # Added .0 for consistency with format: float
                    FeeCalcType: "Percentage"
                    IsActive: false
                    ProductId: 1
