openapi: 3.0.0
info:
  title: Get Product
  description: Retrieves details about a specific product.
  version: 1.0.0
paths:
  GetProduct:
    get:
      summary: Get Product
      tags:
        - Public
      parameters:
        - in: query
          name: OMSId
          schema:
            type: integer
          description: The ID of the Order Management System.
          required: true
        - in: query
          name: ProductId
          schema:
            type: integer
          description: The ID of the product.
          required: true
      responses:
        "200":
          description: Successful retrieval of product details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  omsId:
                    type: integer
                    description: The Order Management System ID.
                  productId:
                    type: integer
                    description: The ID of the product.
                  product:
                    type: string
                    description: The product nickname.
                  productFullName:
                    type: string
                    description: The full product name.
                  productType:
                    type: string
                    enum:
                      - Unknown
                      - NationalCurrency
                      - CryptoCurrency
                      - Contract
                    description: The type of product.
                  decimalPlaces:
                    type: integer
                    description: The number of decimal places.
                  tickSize:
                    type: number
                    format: float
                    description: The smallest increment for trading.
                  noFees:
                    type: boolean
                    description: Are there any fees?
                required:
                  - omsId
                  - productId
                  - productType
                  - decimalPlaces
                  - tickSize
                  - noFees
                example:
                  omsId: 0
                  productId: 0
                  product: null
                  productFullName: null
                  productType: "Unknown"
                  decimalPlaces: 0
                  tickSize: 0.0
                  noFees: false
