openapi: 3.0.0
info:
  title: Get User Affiliate Count
  description: Gets a count of users who have been referred to the exchange by the identified user.
  version: 1.0.0
paths:
  GetUserAffiliateCount: # More descriptive path
    get:
      summary: Get User Affiliate Count
      tags:
        - User
      parameters:
        - in: query
          name: OMSId
          schema:
            type: integer
          description: The ID of the Order Management System.
          required: true
        - in: query
          name: UserId
          schema:
            type: integer
          description: The ID of the user.
          required: true
      responses:
        "200":
          description: Successful retrieval of affiliate count.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Count:
                    type: integer
                    description: The count of referred users.
              example:
                Count: 123 # Or any other integer value
