name: Pull Request and Push
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spell-check:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rojopolis/spellcheck-github-actions@0.42.0
        with:
          config_path: .spellcheck.yml
  markdown-link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: .md-link-check.json